#
# TABLE STRUCTURE FOR: pages
#

DROP TABLE IF EXISTS `pages`;

CREATE TABLE `pages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kategori_id` int(11) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` longtext NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8;

INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 1, 'seputar-ppid', 'Seputar PPID', '<p>Informasi merupakan kebutuhan pokok setiap orang bagi pengembangan pribadi dan lingkungan sosialnya serta merupakan bagian penting bagi Ketahanan Nasional. Hak memperoleh informasi merupakan hak asasi manusia (HAM) dan keterbukaan informasi publik merupakan salah satu ciri penting Negara Demokratis yang menjunjung tinggi kedaulatan rakyat untuk mewujudkan penyelenggaraan Negara yang baik. \r\n</p>\r\n<blockquote>\r\n<p>\r\nPemberlakuan Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik (KIP) pada tanggal 30 April 2010 merupakan momentum penting dalam mendorong keterbukaan di Indonesia, khususnya di Jawa Timur. \r\n</p>\r\n</blockquote><p>\r\nUndang-Undang ini telah memberikan landasan hukum terhadap hak setiap orang untuk memperoleh informasi publik di mana setiap Badan Publik mempunyai kewajiban dalam menyediakan dan melayani permohonan informasi publik secara cepat, tepat waktu, biaya ringan dan dengan cara yang sederhana.\r\n</p><p>\r\nDalam rangka membangun dan mengembangkan sistem informasi dan dokumentasi di Dinas Peternakan Provinsi Jawa Timur, perlu dibuat Standar Layanan Informasi Publik. Standar Layanan Informasi Publik tersebut berupa Standar Operasional Prosedur (SOP) yang bertujuan memberikan petunjuk pelaksana secara administratif bagi PPID di lingkungan Dinas Peternakan Provinsi Jawa Timur dalam melaksanakan Amanat Undang-undang Keterbukaan Informasi Publik.\r\n\r\n</p>\r\n<blockquote>\r\n<p>\r\nSesuai ketentuan dalam Keputusan Menteri Komunikasi dan Informatika Nomor 117 Tahun 2010 tentang Organisasi Pengelola Informasi dan Dokumentasi di mana salah satu tugas Pejabat Pengelola Informasi dan Dokumentasi (PPID) adalah menyediakan akses informasi publik bagi pemohon informasi.\r\n</p>\r\n</blockquote>\r\n<p>\r\n\r\nTerkait dengan tugas tersebut, SKPD Dinas Peternakan Provinsi Jawa Timur menetapkan Layanan Informasi Publik Pengelolaan Informasi dan Dokumentasi di SKPD Dinas Peternakan Provinsi Jawa Timur. Dengan adanya layanan informasi ini, diharapkan Implementasi Undang-Undang Keterbukaan Informasi Publik dapat berjalan efektif dan hak-hak publik terhadap informasi yang berkualitas secara nyata terpenuhi\r\n</p>', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 1, 'kelembagaan-dan-sk', 'Kelembagaan dan SK', '\n<img class=\"card-img-top\" src=\"http://[::1]/ppid/public/assets/img/struktur-ppid.jpg\"><p>Informasi merupakan kebutuhan pokok setiap orang bagi pengembangan pribadi dan lingkungan sosialnya serta merupakan bagian penting bagi Ketahanan Nasional. Hak memperoleh informasi merupakan hak asasi manusia (HAM) dan keterbukaan informasi publik merupakan salah satu ciri penting Negara Demokratis yang menjunjung tinggi kedaulatan rakyat untuk mewujudkan penyelenggaraan Negara yang baik. \n</p>\n<blockquote>\n<p>\nPemberlakuan Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik (KIP) pada tanggal 30 April 2010 merupakan momentum penting dalam mendorong keterbukaan di Indonesia, khususnya di Jawa Timur. \n</p>\n</blockquote><p>\nUndang-Undang ini telah memberikan landasan hukum terhadap hak setiap orang untuk memperoleh informasi publik di mana setiap Badan Publik mempunyai kewajiban dalam menyediakan dan melayani permohonan informasi publik secara cepat, tepat waktu, biaya ringan dan dengan cara yang sederhana.\n</p><p>\nDalam rangka membangun dan mengembangkan sistem informasi dan dokumentasi di Dinas Peternakan Provinsi Jawa Timur, perlu dibuat Standar Layanan Informasi Publik. Standar Layanan Informasi Publik tersebut berupa Standar Operasional Prosedur (SOP) yang bertujuan memberikan petunjuk pelaksana secara administratif bagi PPID di lingkungan Dinas Peternakan Provinsi Jawa Timur dalam melaksanakan Amanat Undang-undang Keterbukaan Informasi Publik.\n\n</p>\n<blockquote>\n<p>\nSesuai ketentuan dalam Keputusan Menteri Komunikasi dan Informatika Nomor 117 Tahun 2010 tentang Organisasi Pengelola Informasi dan Dokumentasi di mana salah satu tugas Pejabat Pengelola Informasi dan Dokumentasi (PPID) adalah menyediakan akses informasi publik bagi pemohon informasi.\n</p>\n</blockquote>\n<p>\n\nTerkait dengan tugas tersebut, SKPD Dinas Peternakan Provinsi Jawa Timur menetapkan Layanan Informasi Publik Pengelolaan Informasi dan Dokumentasi di SKPD Dinas Peternakan Provinsi Jawa Timur. Dengan adanya layanan informasi ini, diharapkan Implementasi Undang-Undang Keterbukaan Informasi Publik dapat berjalan efektif dan hak-hak publik terhadap informasi yang berkualitas secara nyata terpenuhi\n</p>', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 1, 'pedoman-ppid', 'Pedoman PPID', '<blockquote><p>Tugas dan tanggung  jawab PPID sebagaimana dimaksud dalam keputusan sebagai berikut :</p></blockquote>\r\n<ol>\r\n<li>Penyediaan, penyimpanan, pendokumentasian dan pengamanan informasi</li>\r\n<li>Pelayanan Informasi Publik sesuai dengan aturan yang berlaku</li>\r\n<li>Pelayanan Informasi Publik yang cepat, tepat dan sederhana</li>\r\n<li>Mengkoordinasikan pengumpulan seluruh Informasi Publik secara fisik dari setiap unit/satuan kerja meliputi informasi yang wajib disediakan dan diumumkan secara berkala, informasi yang wajib tersedia setiap saat, informasi terbuka lainnya yang diminta pemohon Informasi Publik</li>\r\n<li>Mengkoordinasikan pendataan Informasi Publik yang di kuasai oleh setiap unit/satuan kerja di badan publik dalam rangka pembuatan dan pemutakhiran daftar Informasi Publik setelah di mutakhirkan oleh pimpinan masing-masing unit/satuan kerja sekurang-kurangnya 1 (satu) kali dalam sebulan</li>\r\n<li>Mengkoordinasikan penyediaan dan pelayanan Informasi Publik melalui pengumuman (media yang menjangkau seluruh pemangku kepentingan) dan/atau permohonan</li>\r\n<li>Membantu PPID dalam melaksakan tugas dan kewenangannya</li>\r\n<li>Menyampaikan informasi dan dokumentasi kepada PPID secara berkala dan sesuai kebutuhan</li>\r\n<li>Menentukan atau menetapkan suatu informasi dapat dan tidaknya diakses oleh publik</li>\r\n<li>Mengkonsultasikan informasi yang dikecualikan kepada PPID Provinsi (rahasia jabatan, rahasia pribadi)</li>\r\n</ol>\r\n              </p>', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, 1, 'sop-pelayanan', 'SOP Pelayanan', '<blockquote><p>Tugas dan tanggung  jawab PPID sebagaimana dimaksud dalam keputusan sebagai berikut :</p></blockquote>\r\n<ol>\r\n<li>Penyediaan, penyimpanan, pendokumentasian dan pengamanan informasi</li>\r\n<li>Pelayanan Informasi Publik sesuai dengan aturan yang berlaku</li>\r\n<li>Pelayanan Informasi Publik yang cepat, tepat dan sederhana</li>\r\n<li>Mengkoordinasikan pengumpulan seluruh Informasi Publik secara fisik dari setiap unit/satuan kerja meliputi informasi yang wajib disediakan dan diumumkan secara berkala, informasi yang wajib tersedia setiap saat, informasi terbuka lainnya yang diminta pemohon Informasi Publik</li>\r\n<li>Mengkoordinasikan pendataan Informasi Publik yang di kuasai oleh setiap unit/satuan kerja di badan publik dalam rangka pembuatan dan pemutakhiran daftar Informasi Publik setelah di mutakhirkan oleh pimpinan masing-masing unit/satuan kerja sekurang-kurangnya 1 (satu) kali dalam sebulan</li>\r\n<li>Mengkoordinasikan penyediaan dan pelayanan Informasi Publik melalui pengumuman (media yang menjangkau seluruh pemangku kepentingan) dan/atau permohonan</li>\r\n<li>Membantu PPID dalam melaksakan tugas dan kewenangannya</li>\r\n<li>Menyampaikan informasi dan dokumentasi kepada PPID secara berkala dan sesuai kebutuhan</li>\r\n<li>Menentukan atau menetapkan suatu informasi dapat dan tidaknya diakses oleh publik</li>\r\n<li>Mengkonsultasikan informasi yang dikecualikan kepada PPID Provinsi (rahasia jabatan, rahasia pribadi)</li>\r\n</ol>\r\n              </p>', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (5, 1, 'regulasi', 'Regulasi', '<blockquote><p>Tugas dan tanggung  jawab PPID sebagaimana dimaksud dalam keputusan sebagai berikut :</p></blockquote>\r\n<ol>\r\n<li>Penyediaan, penyimpanan, pendokumentasian dan pengamanan informasi</li>\r\n<li>Pelayanan Informasi Publik sesuai dengan aturan yang berlaku</li>\r\n<li>Pelayanan Informasi Publik yang cepat, tepat dan sederhana</li>\r\n<li>Mengkoordinasikan pengumpulan seluruh Informasi Publik secara fisik dari setiap unit/satuan kerja meliputi informasi yang wajib disediakan dan diumumkan secara berkala, informasi yang wajib tersedia setiap saat, informasi terbuka lainnya yang diminta pemohon Informasi Publik</li>\r\n<li>Mengkoordinasikan pendataan Informasi Publik yang di kuasai oleh setiap unit/satuan kerja di badan publik dalam rangka pembuatan dan pemutakhiran daftar Informasi Publik setelah di mutakhirkan oleh pimpinan masing-masing unit/satuan kerja sekurang-kurangnya 1 (satu) kali dalam sebulan</li>\r\n<li>Mengkoordinasikan penyediaan dan pelayanan Informasi Publik melalui pengumuman (media yang menjangkau seluruh pemangku kepentingan) dan/atau permohonan</li>\r\n<li>Membantu PPID dalam melaksakan tugas dan kewenangannya</li>\r\n<li>Menyampaikan informasi dan dokumentasi kepada PPID secara berkala dan sesuai kebutuhan</li>\r\n<li>Menentukan atau menetapkan suatu informasi dapat dan tidaknya diakses oleh publik</li>\r\n<li>Mengkonsultasikan informasi yang dikecualikan kepada PPID Provinsi (rahasia jabatan, rahasia pribadi)</li>\r\n</ol>\r\n              </p>', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (6, 2, 'hak-pemohon', 'Hak Pemohon', '', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (7, 2, 'datang-langsung', 'Datang Langsung', '', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (8, 2, 'form-permintaan', 'Form Permintaan', '', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (9, 2, 'Pengajuan-keberatan', 'Pengajuan Keberatan', '', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (10, 2, 'mekanisme-proses', 'Mekanisme / Proses', '', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (11, 2, 'penyelesaian-sengketa', 'Penyelesaian Sengketa', '', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (12, 3, 'informasi-berkala', 'Informasi Berkala', '', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (13, 3, 'informasi-serta-merta', 'Informasi Serta Merta', '', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (14, 3, 'informasi-setiap-saat', 'Informasi Setiap Saat', '', NULL, NULL, NULL);
INSERT INTO `pages` (`id`, `kategori_id`, `slug`, `title`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES (15, 3, 'laporan-informasi', 'Laporan Informasi', '', NULL, NULL, NULL);


#
# TABLE STRUCTURE FOR: pages__category
#

DROP TABLE IF EXISTS `pages__category`;

CREATE TABLE `pages__category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama_kategori` varchar(255) NOT NULL,
  `slug_kategori` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

INSERT INTO `pages__category` (`id`, `nama_kategori`, `slug_kategori`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'Profil', 'profil', NULL, NULL, NULL);
INSERT INTO `pages__category` (`id`, `nama_kategori`, `slug_kategori`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'Layanan Informasi', 'layanan-informasi', NULL, NULL, NULL);
INSERT INTO `pages__category` (`id`, `nama_kategori`, `slug_kategori`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'Daftar Informasi', 'daftar-informasi', NULL, NULL, NULL);


